# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: https://about.me/kihoon
# Customize
customize:
    logo:
        width: 165
        height: 60
        url: images/kihoonkim-logo.png
    theme_color: '#006bde'
    highlight: androidstudio
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        facebook: https://www.facebook.com/koreakihoon
        github: https://github.com/kihoonkim
        rss: /

# Widgets
widgets:
    - recent_posts
    - category
    - tagcloud

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here

# Comment
comment:
    disqus: kihoonkim # enter disqus shortname here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    google_analytics: UA-90999360-1 # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
